2024-12-28 21:08:28,332 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Univer\module_12\test_12_4.py", line 25, in test_run
    test_run_value = Runner(8)
                     ^^^^^^^^^
  File "D:\Univer\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-28 21:08:28,341 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Univer\module_12\test_12_4.py", line 13, in test_walk
    test_walk_value = Runner('test_walk_value', -5)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Univer\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
